#!/bin/bash
#aoc mem_bandwidth.cl -o bin_fpga/mem_bandwidth.aocx --board bdw_fpga_v1.0 --report -g
#aoc GO_TRACK_CSV_TO_CSV_FOR.cl -o bin_emu_gotrack_csv_for/GO_TRACK_CSV_TO_CSV_FOR.aocx -march=emulator --board bdw_fpga_v1.0 -v --report -g

#Source Files
VERBOSE := 1
ifeq ($(VERBOSE),0)
ECHO := @
else
ECHO := 
endif

ifeq ($(VERBOSE),0)
VERB := -v
else
VERB := 
endif

ifeq ($(DEBUG),0)
DB := -g
else
DB := 
endif


SRCS := $(wildcard *.cl)


ifeq ($1,fpga)
	TARGET_DIR := fpga_bin
else
	TARGET_DIR := emu_bin
endif

TARGET := $(basename $(SRCS)).aocx
LIBS :=
CXX := aoc
CL_FLAGS := $(VERB) --report -v -g
HW_TARGET := --board bdw_fpga_v1.0 $(CL_FLAGS) 
EMU_TARGET := -march=emulator $(HW_TARGET)


emu: 
	$(ECHO)$(CXX) $(SRCS) -o emu_bin/$(TARGET) $(EMU_TARGET)
fpga:
	$(ECHO)$(CXX) $(SRCS) -o fpga_bin/$(TARGET) $(HW_TARGET)
clean: 
	$(ECHO)rm -rf $(TARGET_DIR)

	

.PHONY : all clean 
